### ISSUE TITLE
Timed out port confusion

### ISSUE THREAD

**Issue by runningman84** [sfudeus/homematic_exporter#28]
I get this error message:
```
 2021-10-31 23:14:00,801 - INFO - Starting thread for data gathering                                                                                                                                            │
│ 2021-10-31 23:14:00,801 - INFO - Exposing metrics on port 9133                                                                                                                                                 │
│ 2021-10-31 23:14:00,801 - INFO - Mapping 0 devices with custom names                                                                                                                                           │
│ 2021-10-31 23:14:00,802 - INFO - Supporting 46 device types: HmIP-eTRV-2,HmIP-FSM,HMIP-PSM,HmIP-RCV-1,HmIP-STH,HmIP-STHD,HmIP-SWD,HMIP-SWDO,HmIP-SWSD,HmIP-SWO-PL,HmIP-SWO-PR,HmIP-WTH-2,HM-CC-RT-DN,HM-Dis-EP │
│ 2021-10-31 23:14:00,811 - DEBUG - Starting new HTTP connection (1): xx.xx.xx.xx:8181                                                                                                                            │
│ Exception in thread Thread-1:                                                                                                                                                                                  │
│ Traceback (most recent call last):                                                                                                                                                                             │
│   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn                                                                                                                 │
│     conn = connection.create_connection(                                                                                                                                                                       │
│   File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 96, in create_connection                                                                                                     │
│     raise err                                                                                                                                                                                                  │
│   File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 86, in create_connection                                                                                                     │
│     sock.connect(sa)                                                                                            
```

Why is it connecting to port 8181? my args are these:
```│       --ccu_host                                                                                                                                                                                               │
│       xx.xx.xx.xx                                                                                                                                                                                               │
│       --ccu_port                                                                                                                                                                                               │
│       2001                                                                                                                                                                                                     │
│       --port                                                                                                                                                                                                   │
│       9133                                                                                                                                                                                                     │
│       --debug 
```

I am wondering why I can access my ccu3 using home assistant just fine...

**Comment by runningman84** [comment]
Ok the solution is to allow access to "Remote Homematic-Script API" in the ccu firewall settings... maybe this could be a good hint for the docs...

**Comment by sfudeus** [comment]
Thanks for the hint, the (optional) need for port 8181 was just recently added. I added some documentation regarding CCU config requirements now.
