### ISSUE TITLE
config file issue

### ISSUE THREAD

**Issue by DanielWeeber** [sfudeus/homematic_exporter#32]
Having a somewhat similar problem to #9 

When I dont include any config file I do get a couple of metrics from the ccu exported just fine, but no devices itself

```
root@nas:~# curl http://127.0.0.1:9789/metrics
(...)
(removing the python_ and process_ lines for sake of readability)
# HELP homematic_devicecount Number of processed/supported devices
# TYPE homematic_devicecount gauge
homematic_devicecount{ccu="192.168.1.30"} 55.0
# HELP homematic_gathering_count_total Amount of gathering runs
# TYPE homematic_gathering_count_total counter
homematic_gathering_count_total{ccu="192.168.1.30"} 2.0
# HELP homematic_gathering_count_created Amount of gathering runs
# TYPE homematic_gathering_count_created gauge
homematic_gathering_count_created{ccu="192.168.1.30"} 1.6416874286899266e+09
# HELP homematic_gathering_errors_total Amount of failed gathering runs
# TYPE homematic_gathering_errors_total counter
# HELP homematic_generate_metrics_seconds Time spent in gathering runs
# TYPE homematic_generate_metrics_seconds summary
homematic_generate_metrics_seconds_count{ccu="192.168.1.30"} 2.0
homematic_generate_metrics_seconds_sum{ccu="192.168.1.30"} 0.2012096792459488
# HELP homematic_generate_metrics_seconds_created Time spent in gathering runs
# TYPE homematic_generate_metrics_seconds_created gauge
homematic_generate_metrics_seconds_created{ccu="192.168.1.30"} 1.6416874286899843e+09
# HELP homematic_read_names_seconds Time spent reading names from CCU
# TYPE homematic_read_names_seconds summary
homematic_read_names_seconds_count{ccu="192.168.1.30"} 1.0
homematic_read_names_seconds_sum{ccu="192.168.1.30"} 0.02728335279971361
# HELP homematic_read_names_seconds_created Time spent reading names from CCU
# TYPE homematic_read_names_seconds_created gauge
homematic_read_names_seconds_created{ccu="192.168.1.30"} 1.6416874286621323e+09
```

When I add --config_file /config/config.json to Dockerfile "command" (and mapping a config.json in /config of course) I dont get any output with homematic_

```
root@nas:~# curl http://127.0.0.1:9789/metrics
(...)
(removing the python_ and process_ lines for sake of readability)
# HELP homematic_devicecount Number of processed/supported devices
# TYPE homematic_devicecount gauge
# HELP homematic_gathering_count_total Amount of gathering runs
# TYPE homematic_gathering_count_total counter
# HELP homematic_gathering_errors_total Amount of failed gathering runs
# TYPE homematic_gathering_errors_total counter
# HELP homematic_generate_metrics_seconds Time spent in gathering runs
# TYPE homematic_generate_metrics_seconds summary
# HELP homematic_read_names_seconds Time spent reading names from CCU
# TYPE homematic_read_names_seconds summary
```

--dump_devices and --dump_device_names works just fine with and without a config file

docker logs without config file

```
2022-01-09 00:29:39,505 - INFO - Starting thread for data gathering
2022-01-09 00:29:39,505 - INFO - Exposing metrics on port 9789
2022-01-09 00:29:39,507 - INFO - Mapping 0 devices with custom names
2022-01-09 00:29:39,508 - INFO - Supporting 46 device types: HmIP-eTRV-2,HmIP-FSM,HMIP-PSM,HmIP-RCV-1,HmIP-STH,HmIP-STHD,HmIP-SWD,HMIP-SWDO,HmIP-SWSD,HmIP-SWO-PL,HmIP-SWO-PR,HmIP-WTH-2,HM-CC-RT-DN,HM-Dis-EP-WM55,HM-Dis-WM55,HM-ES-PMSw1-Pl-DN-R5,HM-ES-TX-WM,HM-LC-Bl1-FM,HM-LC-Dim1PWM-CV,HM-LC-Dim1T-FM,HM-LC-RGBW-WM,HM-LC-Sw1-Pl-DN-R5,HM-LC-Sw1-FM,HM-LC-Sw2-FM,HM-OU-CFM-Pl,HM-OU-CFM-TW,HM-PBI-4-FM,HM-PB-2-WM55,HM-PB-6-WM55,HM-RC-P1,HM-RC-4-2,HM-RC-8,HM-Sec-MDIR-2,HM-Sec-SCo,HM-Sec-SC-2,HM-Sec-SD-2,HM-Sec-TiS,HM-Sen-LI-O,HM-Sen-MDIR-O,HM-Sen-MDIR-WM55,HM-SwI-3-FM,HM-TC-IT-WM-W-EU,HM-WDS10-TH-O,HM-WDS100-C6-O-2,HM-WDS30-OT2-SM,HM-WDS40-TH-I-2
2022-01-09 00:29:39,545 - INFO - Read 214 device names from CCU
2022-01-09 00:29:39,546 - INFO - Gathering metrics
2022-01-09 00:29:39,649 - INFO - Found unsupported top-level device 001FDBE98A7517 of type HmIP-FCI1
2022-01-09 00:29:39,650 - INFO - Found unsupported top-level device HmIP-RCV-1 of type HmIP-RCV-50
2022-01-09 00:30:39,706 - INFO - Gathering metrics
2022-01-09 00:30:39,799 - INFO - Found unsupported top-level device 001FDBE98A7517 of type HmIP-FCI1
2022-01-09 00:30:39,799 - INFO - Found unsupported top-level device HmIP-RCV-1 of type HmIP-RCV-50
2022-01-09 00:31:39,859 - INFO - Gathering metrics
2022-01-09 00:31:39,954 - INFO - Found unsupported top-level device 001FDBE98A7517 of type HmIP-FCI1
2022-01-09 00:31:39,954 - INFO - Found unsupported top-level device HmIP-RCV-1 of type HmIP-RCV-50
2022-01-09 00:32:40,015 - INFO - Gathering metrics
2022-01-09 00:32:40,110 - INFO - Found unsupported top-level device 001FDBE98A7517 of type HmIP-FCI1
2022-01-09 00:32:40,111 - INFO - Found unsupported top-level device HmIP-RCV-1 of type HmIP-RCV-50
2022-01-09 00:33:40,170 - INFO - Gathering metrics
2022-01-09 00:33:40,274 - INFO - Found unsupported top-level device 001FDBE98A7517 of type HmIP-FCI1
2022-01-09 00:33:40,274 - INFO - Found unsupported top-level device HmIP-RCV-1 of type HmIP-RCV-50
2022-01-09 00:34:40,333 - INFO - Gathering metrics
2022-01-09 00:34:40,432 - INFO - Found unsupported top-level device 001FDBE98A7517 of type HmIP-FCI1
2022-01-09 00:34:40,432 - INFO - Found unsupported top-level device HmIP-RCV-1 of type HmIP-RCV-50


```

docker logs with config file

```
2022-01-09 00:36:08,597 - INFO - Processing config file /config/config.json
2022-01-09 00:36:08,599 - INFO - Starting thread for data gathering
2022-01-09 00:36:08,600 - INFO - Exposing metrics on port 9789
2022-01-09 00:36:08,600 - INFO - Mapping 2 devices with custom names
2022-01-09 00:36:08,603 - INFO - Supporting 46 device types: HmIP-eTRV-2,HmIP-FSM,HMIP-PSM,HmIP-RCV-1,HmIP-STH,HmIP-STHD,HmIP-SWD,HMIP-SWDO,HmIP-SWSD,HmIP-SWO-PL,HmIP-SWO-PR,HmIP-WTH-2,HM-CC-RT-DN,HM-Dis-EP-WM55,HM-Dis-WM55,HM-ES-PMSw1-Pl-DN-R5,HM-ES-TX-WM,HM-LC-Bl1-FM,HM-LC-Dim1PWM-CV,HM-LC-Dim1T-FM,HM-LC-RGBW-WM,HM-LC-Sw1-Pl-DN-R5,HM-LC-Sw1-FM,HM-LC-Sw2-FM,HM-OU-CFM-Pl,HM-OU-CFM-TW,HM-PBI-4-FM,HM-PB-2-WM55,HM-PB-6-WM55,HM-RC-P1,HM-RC-4-2,HM-RC-8,HM-Sec-MDIR-2,HM-Sec-SCo,HM-Sec-SC-2,HM-Sec-SD-2,HM-Sec-TiS,HM-Sen-LI-O,HM-Sen-MDIR-O,HM-Sen-MDIR-WM55,HM-SwI-3-FM,HM-TC-IT-WM-W-EU,HM-WDS10-TH-O,HM-WDS100-C6-O-2,HM-WDS30-OT2-SM,HM-WDS40-TH-I-2
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/local/bin/homematic_exporter", line 129, in run
    if reload_names_active:
UnboundLocalError: local variable 'reload_names_active' referenced before assignment
```

here is my config, this is just your example with the added supported devices removed

```
{
  "device_mapping": {
    "00112233445566": "Garden",
    "00778899aaccdd": "Room1"
  }
}

```

**Comment by DanielWeeber** [comment]
```
root@nas:/volume1/docker# docker exec f4ecd5d22cd8 /usr/local/bin/homematic_exporter --ccu_host 192.168.1.30 --ccu_port 2010 --config_file /config/config.json
2022-01-09 00:38:01,900 - INFO - Processing config file /config/config.json
2022-01-09 00:38:01,901 - INFO - Starting thread for data gathering
2022-01-09 00:38:01,902 - INFO - Mapping 2 devices with custom names
2022-01-09 00:38:01,902 - INFO - Supporting 46 device types: HmIP-eTRV-2,HmIP-FSM,HMIP-PSM,HmIP-RCV-1,HmIP-STH,HmIP-STHD,HmIP-SWD,HMIP-SWDO,HmIP-SWSD,HmIP-SWO-PL,HmIP-SWO-PR,HmIP-WTH-2,HM-CC-RT-DN,HM-Dis-EP-WM55,HM-Dis-WM55,HM-ES-PMSw1-Pl-DN-R5,HM-ES-TX-WM,HM-LC-Bl1-FM,HM-LC-Dim1PWM-CV,HM-LC-Dim1T-FM,HM-LC-RGBW-WM,HM-LC-Sw1-Pl-DN-R5,HM-LC-Sw1-FM,HM-LC-Sw2-FM,HM-OU-CFM-Pl,HM-OU-CFM-TW,HM-PBI-4-FM,HM-PB-2-WM55,HM-PB-6-WM55,HM-RC-P1,HM-RC-4-2,HM-RC-8,HM-Sec-MDIR-2,HM-Sec-SCo,HM-Sec-SC-2,HM-Sec-SD-2,HM-Sec-TiS,HM-Sen-LI-O,HM-Sen-MDIR-O,HM-Sen-MDIR-WM55,HM-SwI-3-FM,HM-TC-IT-WM-W-EU,HM-WDS10-TH-O,HM-WDS100-C6-O-2,HM-WDS30-OT2-SM,HM-WDS40-TH-I-2
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/local/bin/homematic_exporter", line 129, in run
    if reload_names_active:
UnboundLocalError: local variable 'reload_names_active' referenced before assignment
2022-01-09 00:38:01,902 - INFO - Exposing metrics on port 8010
```


but

```
root@nas:/volume1/docker# docker exec f4ecd5d22cd8 /usr/local/bin/homematic_exporter --ccu_host 192.168.1.30 --ccu_port 2010 --config_file /config/config.json --dump_device_names
2022-01-09 00:38:28,911 - INFO - Processing config file /config/config.json
{'*OEQ2023315': 'HM-Sec-SD-2-Team *OEQ2023315',
 '*OEQ2023315:0': 'HM-Sec-SD-2-Team *OEQ2023315:0',
 '*OEQ2023315:1': 'HM-Sec-SD-2-Team *OEQ2023315:1',
 '001FDBE98A7517': 'HmIP-FCI1 001FDBE98A7517',
 '001FDBE98A7517:0': 'HmIP-FCI1 001FDBE98A7517:0',
 '001FDBE98A7517:1': 'HmIP-FCI1 001FDBE98A7517:1',
 'BidCoS-RF': 'HM-RCV-50 BidCoS-RF',
 'BidCoS-RF:0': 'HM-RCV-50 BidCoS-RF:0',
(removing the other devices for sake of redability)
```

**Comment by sfudeus** [comment]
Hi @DanielWeeber, thanks for reporting. 
Some questions:
a) Which version did you use? And did you use a custom docker image or one of mine published on docker hub?
b) Do you have authentication enabled? I just saw that this leads to an error without a proper message. 
The following example output is expected when credentials are provided via ccu_host and ccu_pass:
```
2022-01-09 17:30:52,918 - INFO - Exposing metrics on port 8010
2022-01-09 17:30:53,018 - INFO - Read 259 device names from CCU
2022-01-09 17:30:53,018 - INFO - Gathering metrics
```
c) Did you activate the Script API in the CCU? This is required when the device names are fetched. I suppose it is, since `-- dum_device_names` worked for you.

But I think I saw the issue just now, will resume later in the evening :-).

**Comment by DanielWeeber** [comment]
a) latest, from your docker hub
b) no
c) yes

Currently building the docker image and trying out #34

**Comment by DanielWeeber** [comment]
Doesn't seem to throw an error now, but metrics still not showing up

```
(removed process_ and python_ metrics again)
# HELP homematic_devicecount Number of processed/supported devices
# TYPE homematic_devicecount gauge
homematic_devicecount{ccu="192.168.1.30"} 55.0
# HELP homematic_gathering_count_total Amount of gathering runs
# TYPE homematic_gathering_count_total counter
homematic_gathering_count_total{ccu="192.168.1.30"} 1.0
# HELP homematic_gathering_count_created Amount of gathering runs
# TYPE homematic_gathering_count_created gauge
homematic_gathering_count_created{ccu="192.168.1.30"} 1.641759917426584e+09
# HELP homematic_gathering_errors_total Amount of failed gathering runs
# TYPE homematic_gathering_errors_total counter
# HELP homematic_generate_metrics_seconds Time spent in gathering runs
# TYPE homematic_generate_metrics_seconds summary
homematic_generate_metrics_seconds_count{ccu="192.168.1.30"} 1.0
homematic_generate_metrics_seconds_sum{ccu="192.168.1.30"} 0.09353187866508961
# HELP homematic_generate_metrics_seconds_created Time spent in gathering runs
# TYPE homematic_generate_metrics_seconds_created gauge
homematic_generate_metrics_seconds_created{ccu="192.168.1.30"} 1.6417599174266567e+09
# HELP homematic_read_names_seconds Time spent reading names from CCU
# TYPE homematic_read_names_seconds summary
```

```
root@nas:/volume1/docker/homematic-test# docker-compose up --build
Building homematictest-exporter
Sending build context to Docker daemon  24.06kB

Step 1/7 : FROM python:3-slim-buster
 ---> 84b629347b26
Step 2/7 : COPY requirements.txt /tmp
 ---> Using cache
 ---> 3e96a30e44a7
Step 3/7 : RUN pip3 install --no-cache-dir -r /tmp/requirements.txt
 ---> Using cache
 ---> 34b0bffcda23
Step 4/7 : COPY exporter.py /usr/local/bin/homematic_exporter
 ---> Using cache
 ---> e95b2c4863cc
Step 5/7 : COPY config.json /config/config.json
 ---> Using cache
 ---> e7797115f293
Step 6/7 : ENTRYPOINT [ "/usr/local/bin/homematic_exporter" ]
 ---> Using cache
 ---> cfe527805e74
Step 7/7 : EXPOSE 8010
 ---> Using cache
 ---> 3e81ea35dd4b
Successfully built 3e81ea35dd4b
Successfully tagged homematic-test_homematictest-exporter:latest
Recreating homematictest_exporter ... done
Attaching to homematictest_exporter
homematictest_exporter    | 2022-01-09 20:25:17,422 - INFO - Processing config file /config/config.json
homematictest_exporter    | 2022-01-09 20:25:17,424 - INFO - Starting thread for data gathering
homematictest_exporter    | 2022-01-09 20:25:17,424 - INFO - Exposing metrics on port 9789
homematictest_exporter    | 2022-01-09 20:25:17,424 - INFO - Mapping 2 devices with custom names
homematictest_exporter    | 2022-01-09 20:25:17,425 - INFO - Supporting 46 device types: HmIP-eTRV-2,HmIP-FSM,HMIP-PSM,HmIP-RCV-1,HmIP-STH,HmIP-STHD,HmIP-SWD,HMIP-SWDO,HmIP-SWSD,HmIP-SWO-PL,HmIP-SWO-PR,HmIP-WTH-2,HM-CC-RT-DN,HM-Dis-EP-WM55,HM-Dis-WM55,HM-ES-PMSw1-Pl-DN-R5,HM-ES-TX-WM,HM-LC-Bl1-FM,HM-LC-Dim1PWM-CV,HM-LC-Dim1T-FM,HM-LC-RGBW-WM,HM-LC-Sw1-Pl-DN-R5,HM-LC-Sw1-FM,HM-LC-Sw2-FM,HM-OU-CFM-Pl,HM-OU-CFM-TW,HM-PBI-4-FM,HM-PB-2-WM55,HM-PB-6-WM55,HM-RC-P1,HM-RC-4-2,HM-RC-8,HM-Sec-MDIR-2,HM-Sec-SCo,HM-Sec-SC-2,HM-Sec-SD-2,HM-Sec-TiS,HM-Sen-LI-O,HM-Sen-MDIR-O,HM-Sen-MDIR-WM55,HM-SwI-3-FM,HM-TC-IT-WM-W-EU,HM-WDS10-TH-O,HM-WDS100-C6-O-2,HM-WDS30-OT2-SM,HM-WDS40-TH-I-2
homematictest_exporter    | 2022-01-09 20:25:17,426 - INFO - Gathering metrics
homematictest_exporter    | 2022-01-09 20:25:17,519 - INFO - Found unsupported top-level device 001FDBE98A7517 of type HmIP-FCI1
homematictest_exporter    | 2022-01-09 20:25:17,519 - INFO - Found unsupported top-level device HmIP-RCV-1 of type HmIP-RCV-50
homematictest_exporter    | 2022-01-09 20:26:17,580 - INFO - Gathering metrics
homematictest_exporter    | 2022-01-09 20:26:17,675 - INFO - Found unsupported top-level device 001FDBE98A7517 of type HmIP-FCI1
homematictest_exporter    | 2022-01-09 20:26:17,675 - INFO - Found unsupported top-level device HmIP-RCV-1 of type HmIP-RCV-50
```

**Comment by sfudeus** [comment]
Auto-closed with the PR, I still want o look into this :-)

**Comment by sfudeus** [comment]
Ok, sorry for the delay @DanielWeeber , next try :-):

In your logs, I see 55 devices being seen and I can see some HmIP-FCI1 devices. 
Question: 
Do you have any devices from the list of supported ones? 
Because if you only have unsupported ones, then there will be no metrics. 
It might work out of the box, you could try just adding the type to the supported_device_types in your config.

**Comment by DanielWeeber** [comment]
yes, esp. HM-CC-RT-DN

Unfortunately still not working :(

docker compose
```
version: '3.7'
services:
  homematic_exporter:
    hostname: homematic-exporter
    image: sfudeus/homematic_exporter:latest
    container_name: homematic_exporter
    ports:
      - "9789:9789"
    volumes:
      - /volume1/docker/homematic_exporter/bidcos/config.json:/config/config.json
    restart: always
    command: --ccu_host 192.168.1.30 --ccu_port 2010 --port 9789 --config_file /config/config.json
    entrypoint: /usr/local/bin/homematic_exporter
    network_mode: bridge
```

docker logs
```
root@nas:/volume1/docker/homematic_exporter# docker logs -f 84cf151d6ffa
2022-03-07 07:40:14,207 - INFO - Processing config file /config/config.json
2022-03-07 07:40:14,208 - INFO - Starting thread for data gathering
2022-03-07 07:40:14,209 - INFO - Exposing metrics on port 9789
2022-03-07 07:40:14,210 - INFO - Mapping 2 devices with custom names
2022-03-07 07:40:14,211 - INFO - Supporting 47 device types: HmIP-eTRV-2,HmIP-FSM,HMIP-PSM,HmIP-RCV-1,HmIP-STH,HmIP-STHD,HmIP-SWD,HMIP-SWDO,HmIP-SWSD,HmIP-SWO-PL,HmIP-SWO-PR,HmIP-WTH-2,HM-CC-RT-DN,HM-Dis-EP-WM55,HM-Dis-WM55,HM-ES-PMSw1-Pl-DN-R5,HM-ES-TX-WM,HM-LC-Bl1-FM,HM-LC-Dim1PWM-CV,HM-LC-Dim1T-FM,HM-LC-RGBW-WM,HM-LC-Sw1-Pl-DN-R5,HM-LC-Sw1-FM,HM-LC-Sw2-FM,HM-OU-CFM-Pl,HM-OU-CFM-TW,HM-PBI-4-FM,HM-PB-2-WM55,HM-PB-6-WM55,HM-RC-P1,HM-RC-4-2,HM-RC-8,HM-Sec-MDIR-2,HM-Sec-SCo,HM-Sec-SC-2,HM-Sec-SD-2,HM-Sec-TiS,HM-Sen-LI-O,HM-Sen-MDIR-O,HM-Sen-MDIR-WM55,HM-SwI-3-FM,HM-TC-IT-WM-W-EU,HM-WDS10-TH-O,HM-WDS100-C6-O-2,HM-WDS30-OT2-SM,HM-WDS40-TH-I,HM-WDS40-TH-I-2
2022-03-07 07:40:14,212 - INFO - Gathering metrics
2022-03-07 07:40:14,338 - INFO - Found unsupported top-level device 001FDBE98A7517 of type HmIP-FCI1
2022-03-07 07:40:14,338 - INFO - Found unsupported top-level device HmIP-RCV-1 of type HmIP-RCV-50

```

curl
```

root@nas:/volume1/docker/homematic_exporter# curl http://127.0.0.1:9789/metrics
# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 160.0
python_gc_objects_collected_total{generation="1"} 296.0
python_gc_objects_collected_total{generation="2"} 0.0
# HELP python_gc_objects_uncollectable_total Uncollectable object found during GC
# TYPE python_gc_objects_uncollectable_total counter
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
# HELP python_gc_collections_total Number of times this generation was collected
# TYPE python_gc_collections_total counter
python_gc_collections_total{generation="0"} 56.0
python_gc_collections_total{generation="1"} 5.0
python_gc_collections_total{generation="2"} 0.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="10",patchlevel="2",version="3.10.2"} 1.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 2.60542464e+08
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 2.2573056e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.6466388108e+09
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 0.6900000000000001
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 7.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
# HELP homematic_devicecount Number of processed/supported devices
# TYPE homematic_devicecount gauge
homematic_devicecount{ccu="192.168.1.30"} 55.0
# HELP homematic_gathering_count_total Amount of gathering runs
# TYPE homematic_gathering_count_total counter
homematic_gathering_count_total{ccu="192.168.1.30"} 1.0
# HELP homematic_gathering_count_created Amount of gathering runs
# TYPE homematic_gathering_count_created gauge
homematic_gathering_count_created{ccu="192.168.1.30"} 1.6466388142124407e+09
# HELP homematic_gathering_errors_total Amount of failed gathering runs
# TYPE homematic_gathering_errors_total counter
# HELP homematic_generate_metrics_seconds Time spent in gathering runs
# TYPE homematic_generate_metrics_seconds summary
homematic_generate_metrics_seconds_count{ccu="192.168.1.30"} 1.0
homematic_generate_metrics_seconds_sum{ccu="192.168.1.30"} 0.12698721303604543
# HELP homematic_generate_metrics_seconds_created Time spent in gathering runs
# TYPE homematic_generate_metrics_seconds_created gauge
homematic_generate_metrics_seconds_created{ccu="192.168.1.30"} 1.6466388142125008e+09
# HELP homematic_read_names_seconds Time spent reading names from CCU
# TYPE homematic_read_names_seconds summary
```
